services:
  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=amongus
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=amongus_dev
    ports:
      - "5432:5432"
    volumes:
      - data-volume:/var/lib/postgresql/data
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_SOURCE=postgresql://amongus:secret@postgres:5432/amongus_dev?sslmode=disable
    depends_on:
      - postgres
    entrypoint:
      [
        "/app/wait-for.sh",
        "postgres:5432",
        "--",
        "/app/start.sh"
      ]
    command: [ "/app/main" ]
volumes:
  data-volume: